AWSTemplateFormatVersion: "2010-09-09"
Description: craeting the instances and attaching the autoscaling for the instances

#doudt: in autoscaling, there is desired and minimum and maxmimum explain
#doudt: what is the meaning of health check and give the explain

Parameters:
  vpcid:
    Type: String
    Default: 10.0.0.0/19
    Description: cidr value vpc

  SubnetId:
    Type: String
    Default: 10.0.0.0/24
    Description: cidrvalue for subnet

  InstanceType:
    Type: String
    Default: t2.micro
    Description: instance type for thr ec2 instances

   
Resources:
  myautoscalingVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: vpcid
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: "default"
      Tags:
      - Key: "Name"
        Value: "vpcautoscaling"

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: "Name"
        Value: "internetautoscaling"

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: myautoscalingVPC
      InternetGatewayId:
        Ref: InternetGateway 

  mySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myautoscalingVPC
      CidrBlock: 
        Ref: SubnetId
      AvailabilityZone: "ap-south-1a"
      Tags:
      - Key: "Name"
        Value: "subnetautoscaling"

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: myautoscalingVPC
      Tags:
      - Key: "Name"
        Value: "routeautoscaling"

  myRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway  

  mySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: mySubnet
      RouteTableId:
        Ref: RouteTable

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      GroupName: "autoscaling"
      VpcId: 
        Ref: myautoscalingVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  autoscalingKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: Cat

  autoscalingec2instances:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0c768662cc797cd75"
      InstanceType: 
        Ref: InstanceType      
      KeyName: "Cat"
      SubnetId:
        Ref: mySubnet
      SecurityGroupIds:
        - Ref: "InstanceSecurityGroup"
      Tags:
       - Key: "Name"
         Value: "scalingec2"
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html>
          <body>
          <p><b>This text is bold</b></p>
          <p><i>This text is italic</i></p>
          <p>This is<sub> subscript</sub> and <sup>superscript</sup></p></body></html>" > /var/www/html/index.html

  autoscalingEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId:  
        Ref: autoscalingec2instances
  