# UserData:
#         Fn::Base64: |
#           #!/bin/bash
#           sudo yum -y update
#           sudo yum -y install ruby
#           sudo yum -y install wget
#           CODEDEPLOY_BIN="/opt/codedeploy-agent/bin/codedeploy-agent"
#           $CODEDEPLOY_BIN stop
#           yum erase codedeploy-agent -y
#           cd /home/ec2-user
#           wget https://aws-codedeploy-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/latest/install
#           chmod +x ./install
#           sudo ./install auto



#this code works
# UserData:
#         Fn::Base64: !Sub |
#           #!/bin/bash
#           yum update -y
#           yum install -y ruby
#           cd /home/ec2-user
#           curl -O https://aws-codedeploy-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/latest/install
#           chmod +x ./install
#           ./install auto
#           service codedeploy-agent start

AWSTemplateFormatVersion: "2010-09-09"
Description: Creating the RDS


Parameters:
  vpcid:
    Type: String
    Default: 10.0.0.0/19
    Description: cidr value vpc

  SubnetId:
    Type: String
    Default: 10.0.0.0/24
    Description: cidrvalue for subnet

  InstanceType:
    Type: String
    Default: t2.micro
    Description: instance type for thr ec2 instances

Resources:

#creating the vpc
  myautoscalingVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: vpcid
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: "default"
      Tags:
      - Key: "Name"
        Value: "vpcautoscaling"

#creating the internet gateway

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: "Name"
        Value: "internetautoscaling"

#attaching the internetgateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: myautoscalingVPC
      InternetGatewayId:
        Ref: InternetGateway 

#craeting the subnet

  mySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myautoscalingVPC
      CidrBlock: 
        Ref: SubnetId
      AvailabilityZone: "ap-northeast-1a"
      Tags:
      - Key: "Name"
        Value: "subnetautoscaling"

#creating the routetable
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: myautoscalingVPC
      Tags:
      - Key: "Name"
        Value: "routeautoscaling"

#adding the inteernetgateway to the rouetable

  myRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway  

# adding the subnet to the routetable

  mySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: mySubnet
      RouteTableId:
        Ref: RouteTable

#creating the security group

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      GroupName: "autoscaling"
      VpcId: 
        Ref: myautoscalingVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

#creating the key pair
  autoscalingKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: paioor

#creating the instances
  autoscalingec2instances:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-01b32aa8589df6208"
      InstanceType: 
        Ref: InstanceType      
      KeyName: "paioor"
      SubnetId:
        Ref: mySubnet
      SecurityGroupIds:
        - Ref: "InstanceSecurityGroup"
      Tags:
       - Key: "Name"
         Value: "dontdelete"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y ruby
          yum install -y wget
          cd /home/ec2-user
          wget https://aws-codedeploy-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/latest/install
          chmod +x ./install
          ./install auto
          service codedeploy-agent start

#creating the volume
  NewVolume:
    Type: AWS::EC2::Volume
    Properties: 
      Size: 22
      Encrypted: true
      AvailabilityZone: "ap-northeast-1a"
      Tags:
        - Key: "Name"
          Value: "volume"


  # #attching the volume to the ec2
  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      Device: /dev/sdh
      InstanceId: 
        Ref: autoscalingec2instances
      VolumeId: 
        Ref: NewVolume

#creating the EIP and attaching to the ec2 instances

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: 
        Ref: autoscalingec2instances