AWSTemplateFormatVersion: "2010-09-09"
Description: craeting the instances connect to the cloudwatch for the cpu utilization

#parameters
Parameters:
  vpcid:
    Type: String
    Default: 10.0.0.0/19
    Description: cidr value vpc

  SubnetId:
    Type: String
    Default: 10.0.0.0/24
    Description: cidrvalue for subnet

  InstanceType:
    Type: String
    Default: t2.micro
    Description: instance type for thr ec2 instances

   
Resources:

#creating the vpc
  myautoscalingVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: vpcid
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: "default"
      Tags:
      - Key: "Name"
        Value: "vpcautoscaling"

#creating the internetgateway

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: "Name"
        Value: "internetautoscaling"

#attaching the internetgateway to  vpc       

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: myautoscalingVPC
      InternetGatewayId:
        Ref: InternetGateway 

#creating the subnet

  mySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myautoscalingVPC
      CidrBlock: 
        Ref: SubnetId
      AvailabilityZone: "ap-south-1a"
      Tags:
      - Key: "Name"
        Value: "subnetautoscaling"

#creating the routetable

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: myautoscalingVPC
      Tags:
      - Key: "Name"
        Value: "routeautoscaling"

#adding the routes to the routetable

  myRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway  

#adding the subnet  to the subnettableassociation

  mySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: mySubnet
      RouteTableId:
        Ref: RouteTable

#creating the security group add the ssh,http

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      GroupName: "autoscaling"
      VpcId: 
        Ref: myautoscalingVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

#creating the key pair

  autoscalingKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: Apple

#creating the ec2 instances and installing the appache webserver and adding the content in it

  autoscalingec2instances:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0c768662cc797cd75"
      InstanceType: 
        Ref: InstanceType      
      KeyName: "Apple"
      SubnetId:
        Ref: mySubnet
      SecurityGroupIds:
        - Ref: "InstanceSecurityGroup"
      Tags:
       - Key: "Name"
         Value: "autoscalingec2"
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html>
          <body>
          <p><b>This text is bold</b></p>
          <p><i>This text is italic</i></p>
          <p>This is my subscript and superscript</p></body></html>" > /var/www/html/index.html

#create and attching the elastic ip to the instances

  autoscalingEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId:  
        Ref: autoscalingec2instances

#creating the sns topi for the alarm for cloudwatch

  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: cloudwatchlogs
      TopicName: Logs
      Subscription:
        - Protocol: email
          Endpoint: somasekar8331@gmail.com

# creating the alarm for the  cpu utilization

  MyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Ref: "MySNSTopic"
      AlarmDescription: "Alarm for CPU utilization on MyInstance"
      AlarmName: "newAlarm"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Period: 300
      Statistic: Average
      Threshold: 30
      Dimensions:
        - Name: InstanceId
          Value: 
            Ref: autoscalingec2instances

  MydiskAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Ref: "MySNSTopic"
      AlarmDescription: "Alarm for CPU utilization on MyInstance"
      AlarmName: "newdiskAlarm"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: DiskSpaceUtilization
      Namespace: AWS/EC2
      Period: 300
      Statistic: Average
      Threshold: 10
      Dimensions:
        - Name: InstanceId
          Value: 
            Ref: autoscalingec2instances
     


  